Add human lung lower lobe
ABI-Software/scaffoldmaker pull request #103
Opened 2020-11-23 01:29 UTC by arti-sukasem

2020-11-23 22:07 UTC, zekh167 requested changes

2020-11-23 22:07 UTC, zekh167 commented on src/scaffoldmaker/meshtypes/meshtype_3d_lung1.py
> +            # Create nodes
One node (node number 28) should be removed.

2020-11-24 00:28 UTC, rchristie requested changes
One minor fix then we'll pull this in -- see comment.
Note I'm still thinking about the 7 node element, but we can fix this later.

2020-11-24 00:28 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_lung1.py
> +                        print('element ', elementIdentifier, '|| ', nodeIdentifiers)
Comment out or remove debug print statements before each commit.

2020-11-24 00:54 UTC, rchristie approved these changes

2020-11-24 00:54 UTC, merged