Smooth derivative directions, add function options
ABI-Software/scaffoldmaker pull request #110
Opened 2020-12-07 10:05 UTC by rchristie

2020-12-07 10:11 UTC, rchristie commented
Users will need update in ABI-Software/mapclientplugins.meshgeneratorstep#28.

2020-12-07 18:50 UTC, mahyar-osn requested changes
Just minor changes. Otherwise, all good. Reviewed and tested.

2020-12-07 18:50 UTC, mahyar-osn commented on src/scaffoldmaker/utils/derivativemoothing.py
> +    def getExpresson(self, expressionIndex):
Typo: `getExpression`

2020-12-07 18:50 UTC, mahyar-osn commented on src/scaffoldmaker/utils/derivativemoothing.py
> +    def smooth(self, updateDirections=False,maxIterations=10, arcLengthTolerance=1.0E-6):
Add space between `updateDirections=False, maxIterations=10`.

2020-12-07 18:50 UTC, mahyar-osn commented on src/scaffoldmaker/utils/derivativemoothing.py
> +                            otherExpression = edge.getExpresson(otherExpressionIndex)
`getExpresson` Should automatically be fixed as above.

2020-12-09 01:20 UTC, mahyar-osn approved these changes
Looks and works great!

2020-12-09 01:35 UTC, merged