added marker points for both human and mouse, updated mouse parameter…
ABI-Software/scaffoldmaker pull request #138
Opened 2021-05-11 23:41 UTC by arti-sukasem

…s, updated test_lung

2021-05-12 01:03 UTC, rchristie requested changes
Mostly have some issues with the point placement and naming - read comments. With some changes made I'll review again. Comments are in the code.

2021-05-12 01:03 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_lung1.py
> +                nodeIdentifier += 1
This code is common for all species: move to end.

2021-05-12 01:03 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_lung1.py
> +                                                               get_lung_term("apex of left lung"))
I would like all annotation groups common to all species made outside of the species-specific code. Only groups specific to one species should be made within the species-specific code, but even then I would like the annotation groups all made together at the beginning of the section.

2021-05-12 01:16 UTC, arti-sukasem commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("dorsal base of accessory lung", "None"),
FYI, its most dorsal extent on the base is Node 129. Would you still like to stick with Node 130?

2021-05-12 01:18 UTC, arti-sukasem commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("dorsal base of right lung", "None"),
one for both right and left lungs? or add one into each lung?

2021-05-12 02:19 UTC, rchristie commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("dorsal base of accessory lung", "None"),
I don't consider 129 and 125 to be on the base (diaphragm) any more as that region is raised higher.

2021-05-12 02:20 UTC, rchristie commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("apex of right lung", "None"),
No apex of accessory lobe is fine at 165. It's the apex of right lung that needs to move to where node 124 is.

2021-05-12 02:21 UTC, rchristie commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("dorsal base of right lung", "None"),
Ideally both; are you happy to edit the base of the human lung to make a point at the dorsal tip?

2021-05-12 02:22 UTC, rchristie commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("lateral side of right lung", "None"),
FYI please make sure the element the marker is located in is the one in the middle lobe, not any of the other elements currently meeting at that point.

2021-05-12 02:55 UTC, arti-sukasem commented on src/scaffoldmaker/annotation/lung_terms.py
> +    ("dorsal base of right lung", "None"),
Yes, no problem Richard. If they are useful and you think it's worth having them, I will add them

2021-05-13 01:34 UTC, rchristie approved these changes

2021-05-13 01:34 UTC, merged