Embed organ landmarks
ABI-Software/scaffoldmaker pull request #145
Opened 2021-05-27 04:14 UTC by elias-soltani

Can you please review this? The fiducial markers were added to the whole body

2021-05-27 20:19 UTC, rchristie requested changes
These should be defined as AnnotationGroup objects from which we can getName for respective groups. They also must be defined in body_coordinates and use findMeshLocation to get element locations so they work with coarse and fine and any other future parameter sets.

2021-06-02 22:12 UTC, rchristie requested changes
It's looking really good & you'll see how you can now fit with the fine mesh as the marker points move appropriately.
There are some easy fixes for you to make, but the main issue is with the brainstem marker points which aren't appropriate, need to get Arti to get some early changes in.

2021-06-02 22:12 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        if animal == 'rat':
if isRat:

2021-06-02 22:12 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        elif animal == 'human':
elif isHuman:

2021-06-02 22:12 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        nodeIdentifier = cylinder1._endNodeIdentifier + 100
Why + 100? I just put them in after the other nodes, don't need to offest.

2021-06-02 22:12 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        body_coordinates = findOrCreateFieldCoordinates(fieldmodule, name="body_coordinates")
Rename the variable bodyCoordinates for consistency with other variables as body_coordinates looks funny in later code.
The tmp_ prefix in the following code can remain, don't care.

2021-06-02 22:12 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        marker_locations.setSearchMode(FieldFindMeshLocation.SEARCH_MODE_EXACT)
rename marker_locations field variable to findMarkerLocation

2021-06-02 22:38 UTC, elias-soltani commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        animal = 'human'
I defined isDefault as well in case the option is default

2021-06-02 22:54 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +        animal = 'human'
'Default' should set one of the other values as it's not a real parameter set. Make these the first lines in your getDefaultOptions()
```
if parameterSetName == "Default":
    parameterSetName = "Human Coarse"
```
BTW. You may want to change your getDefaultOptions to start with options = {} as I use in several other scaffolds then add each option individually. That way you don't set it to one thing for Coarse, then change it for Fine.

2021-06-02 23:37 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_wholebody1.py
> +                {"group": ("HYPOGLOSSAL_right", ''), "x": [0.016, 0.234, 2.79]},
But where did these terms come from?

2021-06-10 06:01 UTC, rchristie approved these changes
Tidy.

2021-06-10 06:01 UTC, merged