Stomach layers
ABI-Software/scaffoldmaker pull request #168
Opened 2021-11-08 01:20 UTC by mlin865

2021-11-12 02:27 UTC, rchristie requested changes
Looks great.
Only one real issue: The Ostium is not working as expect for me (creating it on its own). If I set more than one layer through the wall of the ostium or vessels, it multiplies the wall thickness. Expected behaviour is for the overall thickness to be as specified, but for the relative thicknesses to proportionately distribute layer thicknesses from the overall thickness.
Everything else is mainly questions, some comments in code, plus:
The rat stomach has gaps in the 'mucosa of stomach' between esophagogastric junction and body. Check that is as expected.

2021-11-12 04:00 UTC, mlin865 commented on src/scaffoldmaker/meshtypes/meshtype_3d_colonsegment1.py
> +            'Tenia coli thickness': 0.6,
Yes the tenia coli thickness has been updated to match the measurements of human colons (recent data from Simon Brookes)

2021-11-12 04:00 UTC, mlin865 commented on tests/test_cecum.py
> +        self.assertAlmostEqual(surfaceArea, 65960.20655074248, delta=1.0E-6)
Noted.

2021-11-12 04:02 UTC, mlin865 commented
I have fixed the issue with ostium and I confirm there is a gap in the mucosa around the esophagus for rat stomach.

2021-11-13 21:55 UTC, rchristie approved these changes

2021-11-13 21:55 UTC, merged