Bladder documentation
ABI-Software/scaffoldmaker pull request #210
Opened 2022-08-28 23:21 UTC by zekh167

Hi Richard. I added the bdocumentation for bladder and added the image as well.

2022-08-28 23:42 UTC, rchristie commented on docs/scaffolds/bladder.rst
> +   Separate scaffold will be provided for the bladder.
A separate bladder-only scaffold is in development.

2022-08-28 23:58 UTC, rchristie requested changes
Looks good, some small improvements in comments.

2022-08-28 23:58 UTC, rchristie commented on docs/scaffolds/bladder.rst
> +The bladder scaffold is provided with parameter sets for the following five species, which are very similar in nature but have small, intricate differences:
, which differ subtly in shape and location of ureter inlets.

2022-08-28 23:58 UTC, rchristie commented on docs/scaffolds/bladder.rst
> +   Separate scaffold will be provided for the bladder.
A separate bladder-only scaffold is in development.

2022-08-28 23:58 UTC, rchristie commented on docs/scaffolds/bladder.rst
> +A material coordinates field is not provided, so to perform embedding at this time, it is necessary to use the generic ``coordinates`` field as material coordinates.
Add: This omission will be fixed in the future bladder-only scaffold.

2022-08-28 23:58 UTC, rchristie commented on docs/scaffolds/bladder.rst
> +
Add as separate paragraph: The urethra is optional and can be turned on with the *Include urethra* setting. By default the ureter inlets are marker points on the inner (luminal) surface, but by checking the *Include ureters* option these can be made as 3D element structures.

2022-08-29 02:16 UTC, zekh167 commented
Thanks Richard. I applied your comments.

2022-08-29 02:21 UTC, rchristie approved these changes
Great, thanks!

2022-08-29 02:21 UTC, merged