Unit stomach
ABI-Software/scaffoldmaker pull request #213
Opened 2022-10-05 04:09 UTC by mlin865

Hi Richard, 

I've scaled stomach scaffolds for all species to have a geometric central path of 2.0 unit and the scaffolds (material coordinates too) are aligned such that the junction between fundus and body along the central path now sits on the origin. The markers' material coordinates are updated to reflect the changes in alignment of the material coordinates. Unit tests are also updated accordingly. Please review. Thanks

Mabelle

2022-10-07 02:39 UTC, mlin865 commented
Hi Richard,

I've undo the translation of material coordinates and have now translated stomach scaffold for all species such that their fundus-body intersection along their central path align with the corresponding point for material coordinates. Please review. Thanks

2022-10-10 02:05 UTC, rchristie requested changes
Small change as noted.

2022-10-10 02:05 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_stomach1.py
> +    wallThickness = options['Wall thickness'] * GEJSettings['Unit scale']
It's unexpected that the wall thickness is multiplied by the unit scale of the GEJ. I suggest having the actual thickness in unit scale for the wall thickness, and dividing by GEJSettings['Unit scale'] when transferring to the GEJ in updateSubScaffoldOptions.
I hadn't thought about the GEJ options all needing rescalin , sorry. I think it's OK if they keep their custom unit scale (as you've done) as long as the parent wall thickness is independent as above.
(Also, in hindsight I would have aligned not just the fundus-body junction on the central path, but also it's direction at that point. Not asking you to do this as we've bigger fish to fry.)

2022-10-10 02:32 UTC, mlin865 commented
Change made, please review. Thanks

2022-10-13 22:46 UTC, rchristie approved these changes
Great.

2022-10-13 22:47 UTC, merged