Vagus scaffold initial publication
ABI-Software/scaffoldmaker pull request #264
Opened 2024-08-30 00:48 UTC by v-chopovda

2025-01-22 22:29 UTC, rchristie requested changes
As discussed can you complete a simple test, read but do the minimum to satisfy my noted issues, then we'll pull it in and start on a new branch with a Nerve_network_builder class which directly fits 3-D box nerves.

2025-01-22 22:29 UTC, rchristie commented on docs/scaffolds/vagus.rst
> +The current bladder scaffold is ``3D Vagus Box 1``` built from ``class MeshType_3d_vagus_box1``.
Not bladder.

2025-01-29 02:17 UTC, v-chopovda commented on src/scaffoldmaker/utils/read_vagus_data.py
> +                        parent_first_node = sorted(parent_branch_nodes)[0]
For now I removed sorting and made a comment about assumption that branch nodes are strictly increasing. This should be guaranteed by 1. segmentation stitcher for xml files, 2. csv data preparation tool. However, I made a note to myself that this could be subject to change.

2025-02-03 03:32 UTC, rchristie approved these changes
Great work & I'm very pleased to get it into the codebase.
We've already discussed the next steps to fit orientation.

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Extracting data...')
I think these print statements and others tracking the progress of the algorithm should go.

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +            print('Estimate_trunk: Vagus top to esophageal plexus')
This would be better off being extrated to it's own method (minus the print statements).

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Building centerlines for scaffold...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Building trunk...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Building branches...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Adding anatomical landmarks...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Adding material coordinates...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Adding extra visualisation groups...')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('Done\n')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print(trunk_nodes_data_bounds)
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('... Fitting trunk, iteration', str(ii + 1))
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +    print('... Adding branches')
rm

2025-02-03 07:12 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        print('.' + branch_name)
rm

2025-02-03 23:46 UTC, rchristie approved these changes
One minor comment... now for the tests.

2025-02-03 23:46 UTC, rchristie commented on src/scaffoldmaker/utils/read_vagus_data.py
> +        logger.warning("Missing input data.")
Minor note: this warning will be followed by errors which assume the data was present.
I'm not fussing now as we hope to eventually have built-in default data.

2025-02-03 23:54 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        logger = logging.getLogger(__name__)
Declare this at the top of the file.

2025-02-03 23:56 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
>              is_full_vagus = False
This really should be a function.

2025-02-03 23:56 UTC, hsorby commented on src/scaffoldmaker/utils/read_vagus_data.py
> +    logger = logging.getLogger(__name__)
This should get declared at the top of the file.

2025-02-03 23:58 UTC, hsorby commented on src/scaffoldmaker/meshtypes/meshtype_3d_nerve1.py
> +        logger = logging.getLogger(__name__)
After the import statements.

2025-02-04 02:01 UTC, rchristie approved these changes
Great.

2025-02-04 02:02 UTC, merged