Trigeminal nerve and spinal nerve scaffolds
ABI-Software/scaffoldmaker pull request #269
Opened 2024-12-11 22:46 UTC by mlin865

2025-01-27 23:43 UTC, rchristie requested changes
The whole spine takes a long time to make. Reducing the number of elements as noted should help.
Can you change to human spine in the network layout from any other parent parameters set? I didn't wait for this.
I note that we should allow zero elements in the shell as they're needless here.
I would normally ask for a test, but as with the point about the shell, we have another plan for these scaffolds in future.

2025-01-27 23:43 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_spinalnerve1.py
> +from scaffoldmaker.utils.tubenetworkmesh import BodyTubeNetworkMeshBuilder, TubeNetworkMeshGenerateData
Groups dorsal/ventral/left/right aren't correct.
Could remove; I think you only need to derive from TubeNetworkMeshBuilder to do this.
However, when you have the human pair or the whole spine it would be nice to label left and right.
Not so sure dorsal-ventral are worth keeping in their current form as there are already meaningful groups with those names for the nerve.

2025-01-27 23:43 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_trigeminalnerve1.py
> +        options["Number of elements along ophthalmic nerve"] = 5
Why so many elements along? 3,2,3,3,3 looks acceptable.

2025-01-27 23:43 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_trigeminalnerve1.py
> +from scaffoldmaker.utils.tubenetworkmesh import BodyTubeNetworkMeshBuilder, TubeNetworkMeshGenerateData
Groups dorsal/ventral/left/right don't make any sense. I think you only need to derive from TubeNetworkMeshBuilder to remove them. [I don't want to do this at the moment, but technically dorsal/ventral could become left/right or medial lateral; the latter are painful as you'd need to define it it's left or right trigeminal.]

2025-01-27 23:43 UTC, rchristie commented on src/scaffoldmaker/meshtypes/meshtype_3d_spinalnerve1.py
> +        options["Number of elements along ventral root"] = 8
Probably too many elements, what about 5,2,4,8 -> 3,1,3,5.
Rename "along dorsal root around DRG" to "along dorsal root beside DRG", as "around" has a special meaning.

2025-01-28 23:33 UTC, mlin865 commented
Hi Richard, all requested changes have been made and ready for your review.

2025-01-29 01:02 UTC, rchristie requested changes
One small fix needed. Please test left/right on Human pair 1.

2025-01-29 02:41 UTC, merged